DOMAIN = "weathercanvasai"
CONF_GPT_MODEL_NAME = "gpt_model_name"
DEFAULT_GPT_MODEL_NAME = "gpt-3.5-turbo"
CONF_SYSTEM_INSTRUCTION = ""
DEFAULT_SYSTEM_INSTRUCTION =""
CONF_MAX_IMAGES_RETAINED = "max_images_retained"
DEFAULT_MAX_IMAGES_RETAINED = 5
